### ISSUE TITLE
Issue with YAML input

### ISSUE THREAD

**Issue by kyauy** [TheJacksonLaboratory/LIRICAL#549]
Dear LIRICAL team,

Thanks for your great work. I wish to try it.

I downloaded the last release of LIRICAL (v1.3.1) and downloaded the needed files through the download command.

I try to use it with the yaml command.
I used the yaml provided in example (https://raw.githubusercontent.com/TheJacksonLaboratory/LIRICAL/master/src/test/resources/yaml/simple.yml).

`java -jar  LIRICAL/LIRICAL.jar yaml -y LIRICAL/patient/simple.yml`

I get this error :
```
WARNING: sun.reflect.Reflection.getCallerClass is not supported. This will impact performance.
java.lang.NullPointerException
	at org.monarchinitiative.lirical.output.HtmlTemplate.<init>(HtmlTemplate.java:87)
	at org.monarchinitiative.lirical.output.LiricalTemplate$Builder.buildGenoPhenoHtmlTemplate(LiricalTemplate.java:176)
	at org.monarchinitiative.lirical.cmd.YamlCommand.writeOutput(YamlCommand.java:94)
	at org.monarchinitiative.lirical.cmd.YamlCommand.runPhenotypeOnly(YamlCommand.java:90)
	at org.monarchinitiative.lirical.cmd.YamlCommand.call(YamlCommand.java:163)
	at org.monarchinitiative.lirical.cmd.YamlCommand.call(YamlCommand.java:33)
	at picocli.CommandLine.executeUserObject(CommandLine.java:1953)
	at picocli.CommandLine.access$1300(CommandLine.java:145)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2352)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2346)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2311)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
	at picocli.CommandLine.execute(CommandLine.java:2078)
	at org.monarchinitiative.lirical.Lirical.main(Lirical.java:39)
```
To be noticed : the phenopacket command worked 
`! java -jar  LIRICAL/LIRICAL.jar phenopacket -p LIRICAL/patient/pfeifferNoVcf.json` but doesn't provide the entrezgeneid in output.

Do you have any clues of why?

Thanks for your help!
Kevin

**Comment by pnrobinson** [comment]
There were two issues. One was a bug that I have fixed -- updated version is now uploaded.
The other was the prefix in your yaml file ``/work/software/phenotype_software/LIRICAL/LIRICAL/test_20210409``
The prefix is intended to be a simple word and not the path to where LIRICAL should write the output.
I will need to update the documtation about the YAML file
thanks for pointing this out.
I will merge everything later today.

**Comment by kyauy** [comment]
Thanks a lot, Mr Robinson for your answer and this fix. The YAML input works with v1.3.2! 
In the HPO only mode, can you confirm that we can't have the EntrezGeneID in the prediction? If so, I will use the mim2gene_medgen to get the gene associated.
Thanks again!

**Comment by yuanxiao1988** [comment]
> Thanks a lot, Mr Robinson for your answer and this fix. The YAML input works with v1.3.2!
> In the HPO only mode, can you confirm that we can't have the EntrezGeneID in the prediction? If so, I will use the mim2gene_medgen to get the gene associated.
> Thanks again!

In my case, the v1.3.2 is still not working in HPO-only mode. 

As the same with your case, the EntrezGeneID column of the running result shows all "n/a". I think it means the running is not fully succeeded. This is my error info:

`[ERROR]YamlCommand - YamlCommand.javaorg.monarchinitiative.lirical.cmd.YamlCommand.writeOutput(YamlCommand.java:101) - Done analysis of /work/software/phenotype_software/LIRICAL/LIRICAL_new/LIRICAL/test_20210409.html`

Dear Prof. Robinson @pnrobinson, please help to check it this problem.

**Comment by pnrobinson** [comment]
In the phenotype only mode, LIRICAL does not output genes and therefore it write "n/a" (not available). LIRICAL output genes if you use it with a VCF file as input.

**Comment by yuanxiao1988** [comment]
> In the phenotype only mode, LIRICAL does not output genes and therefore it write "n/a" (not available). LIRICAL output genes if you use it with a VCF file as input.

Thank you so much!

**Comment by kyauy** [comment]
Thanks a lot for these informations!
